version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app # mount codebase for hot reload
      - ./local_model_medium:/usr/src/app/local_model_medium    # Mount the local_model directory
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: flask run --host=0.0.0.0 --reload
