# lists.py

general = ['Air Traffic Control communications', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '90', '180', '270', '360']
nato = ['Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot', 'Golf', 'Hotel', 'India', 'Juliett', 'Kilo', 'Lima', 'Mike', 'November', 'Oscar', 'Papa', 'Quebec', 'Romeo', 'Sierra', 'Tango', 'Uniform', 'Victor', 'Whiskey', 'Xray', 'Yankee', 'Zulu']
atc_words = [
	"acknowledge", "affirmative", "affirm", "altitude", "approach", "apron", "arrival",
	"bandbox", "base", "bearing", "cleared", "climb", "contact", "control",
	"crosswind", "cruise", "descend", "departure", "direct", "disregard",
	"downwind", "estimate", "final", "flight", "frequency", "go around",
	"heading", "hold", "identified", "immediate", "information", "instruct",
	"intentions", "land", "level", "maintain", "mayday", "message", "missed",
	"navigation", "negative", "obstruction", "option", "orbit", "pan-pan",
	"pattern", "position", "proceed", "radar", "readback", "received",
	"report", "request", "required", "runway", "squawk", "standby", "takeoff",
	"taxi", "threshold", "traffic", "transit", "turn", "vector", "visual",
	"waypoint", "weather", "wilco", "wind", "with you", "speed",
	"heavy", "light", "medium", "emergency", "fuel", "identifier",
	"limit", "monitor", "notice", "operation", "permission", "relief",
	"route", "signal", "stand", "system", "terminal", "test", "track",
	"understand", "verify", "vertical", "warning", "zone", "no", "yes", "unable",
	"clearance", "conflict", "coordination", "cumulonimbus", "deviation", "enroute",
	"fix", "glideslope", "handoff", "holding", "IFR", "jetstream", "knots",
	"localizer", "METAR", "NOTAM", "overfly", "pilot", "QNH", "radial",
	"sector", "SID", "STAR", "tailwind", "transition", "turbulence", "uncontrolled",
	"VFR", "wake turbulence", "X-wind", "yaw", "Zulu time", "airspace",
	"briefing", "checkpoint", "elevation", "FL",
	"ground control", "hazard", "ILS", "jetway", "kilo", "logbook", "missed approach",
	"nautical mile", "offset", "profile", "quadrant", "RVR",
	"static", "touchdown", "upwind", "variable", "wingtip", "Yankee", "zoom climb",
	"airspeed", "backtrack", "ETOPS", "gate", "holding pattern",
	"jumpseat", "minimums", "pushback", "RNAV", "slot time", "taxiway", "TCAS",
	"wind shear", "zero fuel weight", "ETA",
	"flight deck", "ground proximity warning system", "jet route",
	"landing clearance", "Mach number", "NDB", "obstacle clearance",
	"PAPI", "QFE", "radar contact",
	'ATC', 'pilot', 'call sign', 'altitude', 'heading', 'speed', 'climb to', 'descend to',
	'maintain', 'tower', 'ground', 'runway', 'taxi', 'takeoff', 'landing',
	'flight level', 'traffic', 'hold short', 'cleared for',
	'roger', 'visibility', 'weather', 'wind', 'gusts',
	'icing conditions', 'deicing', 'VFR', 'IFR', 'no-fly zone',
	'restricted airspace', 'flight path', 'direct route', 'vector', 'frequency change',
	'final approach', 'initial climb to', 'contact approach', 'FIR', 'control zone', 'TMA',
	'missed approach', 'minimum safe altitude', 'transponder',
	'reduce speed to', 'increase speed to',
	'flight conditions', 'clear of conflict', 'resume own navigation', 'request altitude change',
	'request route change', 'flight visibility', 'ceiling', 'severe weather', 'convective SIGMET',
	'AIRMET', 'QNH', 'QFE', 'transition altitude', 'transition level',
	'NOSIG', 'TFR', 'special use airspace',
	'MOA', 'IAP', 'visual approach',
	'NDB', 'VOR',
	'ATIS', 'engine start clearance',
	'line up and wait', 'UNICOM', 'cross runway', 'departure frequency',
	'arrival frequency', 'go-ahead', 'hold position', 'check gear down',
	'touch and go', 'circuit pattern', 'climb via SID',
	'descend via STAR', 'speed restriction', 'flight following', 'radar service terminated', 'squawk VFR',
	'change to advisory frequency', 'report passing altitude', 'report position',
	'ATD', 'block altitude', 'cruise climb', 'direct to', 'execute missed approach',
	'in-flight refueling', 'joining instructions', 'lost communications', 'MEA', 'next waypoint', 'OCH',
	'procedure turn', 'radar vectoring', 'radio failure', 'short final', 'standard rate turn',
	'TRSA', 'undershoot', 'VMC',
	'wide-body aircraft', 'yaw damper', 'zulu time conversion', 'RNAV',
	'RNP', 'barometric pressure', 'control tower handover', 'datalink communication',
	'ELT', 'FDR', 'GCI',
	'hydraulic failure', 'IMC', 'knock-it-off',
	'LVO', 'MAP', 'NAVAIDS',
	'oxygen mask deployment', 'PAR', 'QRA',
	'runway incursion', 'SAR', 'tail strike', 'upwind leg', 'vertical speed',
	'wake turbulence category', 'X-ray cockpit security', 'yield to incoming aircraft', 'zero visibility takeoff',
	'good day', 'no delay', 'fault'
]

collated_list = general + nato + atc_words
collated_list_string = ' '.join(collated_list)

# Number mappings
number_mapping = {
    r'\bzero\b': '0',
    r'\bone\b': '1',
    r'\btwo\b': '2',
    r'\bthree\b': '3',
    r'\bfour\b': '4',
    r'\bfive\b': '5',
    r'\bsix\b': '6',
    r'\bseven\b': '7',
    r'\beight\b': '8',
    r'\bnine\b': '9',
    r'\bten\b': '10',
    r'\beleven\b': '11',
    r'\btwelve\b': '12',
    r'\bthirteen\b': '13',
    r'\bfourteen\b': '14',
    r'\bfifteen\b': '15',
    r'\bsixteen\b': '16',
    r'\bseventeen\b': '17',
    r'\beighteen\b': '18',
    r'\bnineteen\b': '19',
    r'\btwenty\b': '20ident',
    r'\bthirty\b': '30ident',
    r'\bforty\b': '40ident',
    r'\bfifty\b': '50ident',
    r'\bsixty\b': '60ident',
    r'\bseventy\b': '70ident',
    r'\beighty\b': '80ident',
    r'\bninety\b': '90ident',
    r'\bhundred\b': '00ident_hundo',
    r'\bthousand\b': '000ident_thou',
}

